import { StockNews } from '@/types/stocks';

export const news: StockNews[] = [
  {
    id: 'n-1',
    title: 'Apple Reports Record Q4 Earnings, iPhone 15 Sales Exceed Expectations',
    summary: 'Apple Inc. announced record-breaking fourth quarter results driven by strong iPhone 15 Pro demand and services growth. Revenue reached $89.5 billion, beating analyst estimates of $88.1 billion.',
    source: 'Bloomberg',
    url: '#',
    publishedAt: '2024-12-03T14:30:00Z',
    sentiment: 'positive',
    symbols: ['AAPL'],
  },
  {
    id: 'n-2',
    title: 'NVIDIA Unveils Next-Gen AI Chip, Sending Shares Higher',
    summary: 'NVIDIA Corporation announced its next-generation AI accelerator chip, promising 3x performance improvement over current models. The announcement comes as demand for AI computing continues to surge.',
    source: 'Reuters',
    url: '#',
    publishedAt: '2024-12-03T12:15:00Z',
    sentiment: 'positive',
    symbols: ['NVDA'],
  },
  {
    id: 'n-3',
    title: 'Fed Signals Potential Rate Cuts in 2024, Markets Rally',
    summary: 'Federal Reserve officials hinted at potential interest rate cuts in the coming months as inflation shows signs of cooling. The announcement boosted financial sector stocks.',
    source: 'CNBC',
    url: '#',
    publishedAt: '2024-12-03T10:00:00Z',
    sentiment: 'positive',
    symbols: ['JPM', 'BAC', 'GS', 'MS'],
  },
  {
    id: 'n-4',
    title: 'Tesla Faces Increased Competition in China EV Market',
    summary: 'Tesla is facing growing competition from Chinese EV manufacturers, with BYD and Nio gaining market share. Analysts express concerns about margin pressure in the worlds largest EV market.',
    source: 'Financial Times',
    url: '#',
    publishedAt: '2024-12-03T08:45:00Z',
    sentiment: 'negative',
    symbols: ['TSLA'],
  },
  {
    id: 'n-5',
    title: 'Microsoft Azure Revenue Grows 29%, Cloud Competition Intensifies',
    summary: 'Microsoft reported strong Azure cloud revenue growth of 29% year-over-year, though slightly below analyst expectations. The company continues to invest heavily in AI integration across its product suite.',
    source: 'Wall Street Journal',
    url: '#',
    publishedAt: '2024-12-02T16:30:00Z',
    sentiment: 'neutral',
    symbols: ['MSFT'],
  },
  {
    id: 'n-6',
    title: 'Amazon Prime Day Sets New Sales Record',
    summary: 'Amazon reported record sales during its recent Prime Day event, with estimated revenue exceeding $14 billion. Third-party seller participation also hit an all-time high.',
    source: 'TechCrunch',
    url: '#',
    publishedAt: '2024-12-02T14:00:00Z',
    sentiment: 'positive',
    symbols: ['AMZN'],
  },
  {
    id: 'n-7',
    title: 'Google Faces Antitrust Ruling, Search Monopoly Under Scrutiny',
    summary: 'A federal court ruled that Google has maintained an illegal monopoly in the search market. The decision could have significant implications for Alphabet business model.',
    source: 'New York Times',
    url: '#',
    publishedAt: '2024-12-02T11:30:00Z',
    sentiment: 'negative',
    symbols: ['GOOGL'],
  },
  {
    id: 'n-8',
    title: 'Meta Launches New AI Features for Instagram and Facebook',
    summary: 'Meta Platforms unveiled a suite of new AI-powered features for its social media platforms, including advanced content recommendations and creator tools.',
    source: 'The Verge',
    url: '#',
    publishedAt: '2024-12-02T09:00:00Z',
    sentiment: 'positive',
    symbols: ['META'],
  },
  {
    id: 'n-9',
    title: 'Oil Prices Drop on Demand Concerns, Energy Stocks Slide',
    summary: 'Crude oil prices fell 3% on concerns about weakening global demand. Major energy companies including Exxon and Chevron saw their shares decline in response.',
    source: 'Reuters',
    url: '#',
    publishedAt: '2024-12-01T15:45:00Z',
    sentiment: 'negative',
    symbols: ['XOM', 'CVX'],
  },
  {
    id: 'n-10',
    title: 'Healthcare Sector Rallies on Medicare Policy Changes',
    summary: 'Healthcare stocks rallied following announcements of favorable Medicare policy changes for 2024. UnitedHealth and other major insurers led the gains.',
    source: 'MarketWatch',
    url: '#',
    publishedAt: '2024-12-01T13:00:00Z',
    sentiment: 'positive',
    symbols: ['UNH', 'CVS', 'HUM'],
  },
  {
    id: 'n-11',
    title: 'Visa and Mastercard Settle Merchant Fee Lawsuit',
    summary: 'Visa and Mastercard reached a settlement in a long-running lawsuit over merchant transaction fees. The settlement totals approximately $30 billion.',
    source: 'Bloomberg',
    url: '#',
    publishedAt: '2024-12-01T10:30:00Z',
    sentiment: 'neutral',
    symbols: ['V', 'MA'],
  },
  {
    id: 'n-12',
    title: 'Semiconductor Stocks Surge on AI Chip Demand',
    summary: 'Semiconductor stocks posted strong gains as artificial intelligence applications continue to drive demand for advanced chips. AMD and Intel also benefited from the rally.',
    source: 'Barrons',
    url: '#',
    publishedAt: '2024-11-30T16:00:00Z',
    sentiment: 'positive',
    symbols: ['NVDA', 'AMD', 'INTC', 'QCOM'],
  },
  {
    id: 'n-13',
    title: 'Boeing Delays 777X Delivery, Faces More Production Challenges',
    summary: 'Boeing announced further delays to its 777X program, pushing initial deliveries to 2025. The company continues to face quality control and supply chain issues.',
    source: 'Aviation Week',
    url: '#',
    publishedAt: '2024-11-30T14:15:00Z',
    sentiment: 'negative',
    symbols: ['BA'],
  },
  {
    id: 'n-14',
    title: 'Disney+ Subscriber Growth Beats Expectations',
    summary: 'The Walt Disney Company reported stronger-than-expected subscriber growth for Disney+, adding 7.5 million new subscribers. Streaming profitability targets remain on track.',
    source: 'Variety',
    url: '#',
    publishedAt: '2024-11-30T11:00:00Z',
    sentiment: 'positive',
    symbols: ['DIS'],
  },
  {
    id: 'n-15',
    title: 'Costco Reports Strong Same-Store Sales Growth',
    summary: 'Costco Wholesale reported same-store sales growth of 5.8%, beating analyst expectations. Membership renewal rates remain at record highs.',
    source: 'Retail Dive',
    url: '#',
    publishedAt: '2024-11-29T15:30:00Z',
    sentiment: 'positive',
    symbols: ['COST'],
  },
  {
    id: 'n-16',
    title: 'Pharmaceutical Giants Partner on Cancer Drug Development',
    summary: 'Merck and Bristol-Myers Squibb announced a strategic partnership to develop next-generation cancer treatments. The deal includes upfront payments of $2.5 billion.',
    source: 'BioPharma Dive',
    url: '#',
    publishedAt: '2024-11-29T12:00:00Z',
    sentiment: 'positive',
    symbols: ['MRK', 'BMY'],
  },
  {
    id: 'n-17',
    title: 'PayPal Announces Share Buyback Program',
    summary: 'PayPal Holdings announced a $5 billion share buyback program, signaling confidence in the companys long-term prospects despite competitive pressures in digital payments.',
    source: 'CNBC',
    url: '#',
    publishedAt: '2024-11-29T09:30:00Z',
    sentiment: 'positive',
    symbols: ['PYPL'],
  },
  {
    id: 'n-18',
    title: 'Starbucks Expands in China Despite Economic Headwinds',
    summary: 'Starbucks announced plans to open 1,000 new stores in China over the next year, betting on long-term growth despite short-term economic challenges in the region.',
    source: 'Bloomberg',
    url: '#',
    publishedAt: '2024-11-28T14:45:00Z',
    sentiment: 'neutral',
    symbols: ['SBUX'],
  },
  {
    id: 'n-19',
    title: 'Intel Receives Government Funding for US Chip Production',
    summary: 'Intel Corporation received $8.5 billion in government funding under the CHIPS Act to expand semiconductor manufacturing in the United States.',
    source: 'Reuters',
    url: '#',
    publishedAt: '2024-11-28T11:15:00Z',
    sentiment: 'positive',
    symbols: ['INTC'],
  },
  {
    id: 'n-20',
    title: 'Salesforce AI Features Drive Enterprise Adoption',
    summary: 'Salesforce reported strong enterprise adoption of its Einstein AI features, with over 50,000 customers now using AI-powered CRM capabilities.',
    source: 'TechCrunch',
    url: '#',
    publishedAt: '2024-11-28T08:00:00Z',
    sentiment: 'positive',
    symbols: ['CRM'],
  },
];

export default news;
